@echo off
set project=DuckingSpace-repo
set build_path=D:\DuckingSpace-repo\DspNetworks\Binaries
set msbuild="C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MsBuild.exe"
set vs_args=/p:Configuration="Release" /verbosity:minimal
set PreferredToolArchitecture=x64
set VisualStudioVersion=17.0

"D:\HISE-develop\tools\Projucer\Projucer.exe" --resave "%build_path%\AutogeneratedProject.jucer"

echo Compiling 64bit  %project% ...
set Platform=X64
%msbuild% "%build_path%\Builds\VisualStudio2022\%project%.sln" %vs_args%



pause
